#!/bin/bash

##
## Runs the heatmap creating utility
##

inputdatadirectory=data/
outputdirectory=output/imgs
pixelstometers=20
metersofcontext=4

echo
echo -e "Removing previous output..."
rm -r $outputdirectory/*
echo -e "\tDone."

echo -e "Creating heatmaps..."
p5d2htm $inputdatadirectory $outputdirectory -ptm $pixelstometers -context $metersofcontext
echo -e "\tDone."
