#!/bin/bash

#rm imgs/*.png
#rm grids/*.grd

echo "Converting..."
for f in grids/*.grd; 
do 
    #echo "Converting $f...";
    filename=$(basename $f .grd)
    ./pfm2pfm $f imgs/$filename.png
done

#mv *.png imgs/
