#!/bin/bash

echo "Cleaning up..."
scripts/clean_all

echo "Analyzing..."

#for c in $(cat data/categories.csv); do
#   echo category : $c
#done

bin/p5danalyze output/grids/ -heat -ptm 20 -context 4 2> output/err-log.txt

echo "Converting Grids..."
scripts/convert_all
