#! /usr/bin/awk -f

# This is a simple averaging script that reduces the records of each id
# to a single entry per other category

BEGIN {
    FS=","
}

#NR>1{
    pri_cat=$1
    ref_cat=$2
    key=pri_cat "," ref_cat

    sum_1[key] += $3
    sum_2[key] += $4
    count[key]++

#}
END {
    print "pri_cat,ref_cat,1,2"
    for (key in sum)
        print key "," sum_1[key]/cnt[key] "," sum_2[key]/cnt[key]
}
