#
# Application name and list of source files.
#

NAME=p5danalyze
CCSRCS=$(NAME).cpp R2Aux.cpp IOAux.cpp P5DAux.cpp Heatmap.cpp Prepositions.cpp


#
# Dependency libraries
#

PKG_LIBS=-lR3Graphics -lR3Shapes -lR2Shapes -lRNBasics -ljpeg -lpng


#
# R3 application makefile
#

include ../../makefiles/Makefile.apps


