#!/bin/bash

echo -e "\tRemoving all images..."
for i in output/imgs/*.jpg; do rm "$i"; done

echo -e "\tRemoving all grids..."
for i in output/grids/*.grd; do rm "$i"; done

echo -e "\tRemoving stats files..."
rm output/stats/categories.csv
rm output/stats/pairs.csv

echo -e "\tRemoving log files..."
rm output/err-log.txt
