#
# Application name and list of source files.
#

NAME=p5d2htm
CCSRCS=$(NAME).cpp Drawing.cpp IOAux.cpp P5DAux.cpp Heatmap.cpp GraphAux.cpp 


#
# Dependency libraries
#

PKG_LIBS=-lR3Graphics -lR3Shapes -lR2Shapes -lRNBasics -ljpeg -lpng


#
# R3 application makefile
#

include ../../makefiles/Makefile.apps


