#! /bin/bash

[ $# -eq 0 ] && { echo "Usage: $0 category"; exit 1; }

category=$1

python_dir="py"
csv_dir="csv"
scripts_dir="scripts"

src_csv_filename="sample.csv"
dst_csv_filename=$category.csv
report_filename="output.csv"

##
##  FILTER BY CATEGORY
##

rm $csv_dir/$dst_csv_filename ;

echo "Filtering $csv_dir/$src_csv_filename for '$category'..." 
$scripts_dir/filter -v pri_cat=$category $csv_dir/$src_csv_filename > $csv_dir/$dst_csv_filename

##
##  COLLAPSE ROWS
## 
echo "Collapsing (Averaging) $csv_dir/$dst_csv_filename..."
$scripts_dir/average -v pri_cat=$category $csv_dir/$dst_csv_filename > $csv_dir/test_$dst_filename

##
##  ANALYZE CATEGORY
## 

python $python_dir/analyze.py $csv_dir/$dst_csv_filename $report_filename $category
